### PR TITLE
jQuery & jQuery UI Updates

### PR DESCRIPTION
**Pull request by noelleleigh**
###### Explanation About What Code Achieves:

During the UI setup part of Bottery startup, I noticed there were several 404 errors looking for assets in the non-existent `/css/images/` directory. I assumed these were icon tilesets from jQuery UI that for whatever reason were not included in the repository. To test this hypothesis, I downloaded a minimal themed version of the latest jQuery UI (1.12.1) and put it in my development repository. The 404 errors went away, and the panels now have **little corner grabbers** indicating their resizability. 

Unfortunately, this update also made the sliders in the Controls panel visually unresponsive for some reason. I couldn't nail down the cause of this, so I replaced the jQuery UI sliders with **native sliders** with nearly the same functionality (fires events when the mouse button is released instead of on every move of the slider).

These larger, native sliders also pushed down the buttons at the bottom of the Controls panel past the edge of the panel, so I **resized and repositioned** the panel to fit all of its components. I also took the liberty of slightly tweaking the rest of the panels' **sizes and positions** to maintain consistent margins.

Since I had updated jQuery UI to the latest version, I decided to try **updating jQuery** proper (3.2.1) to see if there were any other issues. I did not notice any adverse effects after swapping in the new version, so I included it in this PR

###### Steps To Test:

**Before PR:**
layout

**After PR:**
layout_fixed

###### TODOs:

  - None

### CODE REVIEW

**Comment by noelleleigh** [comment]
@calvinashmore Can I get some feedback on this, and my other PRs I've submitted?

**Comment by calvinashmore** [comment]
Hey there, sorry for the delay. I wanted to take a closer look at this one since it's a significant change to replace the jquery version. I haven't had the chance to actually test it out yet, but I hope to do so by the end of day today

**Comment by calvinashmore** [comment]
Also your contributions have been really valuable and I'm glad that you're helping :)

**Comment by calvinashmore** [comment]
okay, sorry for the crazy delay on this one! I was able to test it and it looks great

**Pull request merged**
